vocabularies/voc4cat.ttl
The initial submission still contained an example.org-URI for the concept scheme (`https://example.org/test_`).
Only in presence of the correct concept scheme IRI, concept and collection IRIs will be converted to CURIEs. The concept-scheme-IRI is used as prefix when converting the Excel-vocabulary-file to turtle.
Besides fixing an obvious bug, this change makes the HTML docs and the turtle file looks much cleaner.
=> Fix concept scheme IRI

README.md
The pull requests for setting up the redirect were accepted today: https://github.com/perma-id/w3id.org/pull/3541 and https://github.com/perma-id/w3id.org/pull/3542
For the Excel file download I have not configured a redirect and content negotiation. I am not convinced that the Excel file which is by design only a temporary artifact needs a permanent url.
=> Update urls to use w3id.org

README.md
Urls were still pointing to voc4cat-template.
=> Update README.md (fix badge)

README.md
Add link to README for checking voc4cat with [SKOS testing tool](http://skos-play.sparna.fr/skos-testing-tool) which implements a web interface for [qSKOS](https://github.com/cmader/qSKOS),
=> Add link to check voc4cat with qSKOS

README.md
Motivated by https://github.com/nfdi4cat/voc4cat-playground/pull/5
=> Stop pointing to playground & other readme fixes

README.md
@SArndt-TIB  - I will leave this open for some days to wait for your comments.
Let me know if you have some badge symbol I could use to link to the service at the top of the readme file (like the ones that link to PyPI and to the SKOS standard).
=> Add info about access via TIB terminology service

.github/workflows/ci-pr.yml, .github/workflows/merge.yml, .github/workflows/publish.yml
Update gh-actions to voc4cat-tool 0.8.3. 
This also changes the action `ci-pr.yaml` to re-create xlsx also if only turtle files were changed in PR commits.
Closes #59
=> Issue59 ci xlsx rebuild

README.md, docs/for_maintainers/README.md, docs/for_maintainers/voc4cat maintenance - Handling of ID-requests.md
@nmoust - You could try this out for the next ID-request. Is there something you would change now? 
Closes #86
=> Add guide how to handle ID-requests

.github/ISSUE_TEMPLATE/improvement_guidelines.yaml, README.md
Both links use the DOI that refers to the whole record and redirects to the latest published version.
Closes #90
=> Fix guidelines link & add link to step-by-step guide

docs/requirements.txt
Sorry, I did not spot it before. Of course this made the job fail here.
On the pro side, merging this PR will show if updates in docs correctly trigger the site build now.
=> Remove local info from requirements file

docs/conf.py, docs/docs_maintenance/creating-docs-locally.md, docs/docs_usage/guidelines.md, docs/docs_usage/how-to-contribute.md, docs/requirements.txt
This fixes some typos in the documentation, adjusts the copyright text in the footer and adds the doc-build date to the footer.
=> Docs: minor fixes & update Sphinx to 8.1.3

docs/requirements.txt
This updates jinja2 for the documentation build from 3.1.4 to 3.1.5 to address the [security report](https://github.com/nfdi4cat/repo4cat/security).
=> Upgrade to safe jinja2 version

justfile
This update taken over from the [voc4cat-template](https://github.com/nfdi4cat/voc4cat-template/) mainly adds a `justfile` for the [just command runner](https://github.com/casey/just). In the justfile, [uv](https://docs.astral.sh/[uv](https://docs.astral.sh/uv/)/) is used to install voc4cat and to run the voc4cat commands.
The justfile helps to tun (almost) the same commands as are used in the GitHub workflow locally on your computer. This makes local testing of a modified vocabulary-xlsx file much easier. Read the header of the justfile for more info on setting up your environment.
Once you have just installed run the command `just` at the root of the git-project to list the available commands:
```bash
Available recipes:
all     # Run combination of steps as in gh-actions: check xlsx, …
```
=> Template update adding a justfile for the just command runner

.github/CODEOWNERS
Up to now all members of the nfdi4cat organization are suggested as possible reviewers for pull requests. This does not make much sense. Instead only those with voc4cat knowledge should be suggested.
To influence who is suggested as reviewer a `.github/CODEOWNERS` file cab be added to the repository which allows to assign users or teams to all contents in a repository (or even to only parts of it). The initial CODEOWNERS file added in this PR assigns the code-ownership to the new team [nfdi4cat/voc4cat-curators](https://github.com/orgs/nfdi4cat/teams/voc4cat-curators).
=> Add a CODEOWNERS file to select suitable PR reviewers

.github/workflows/ci-pr.yml, .github/workflows/merge.yml, .github/workflows/publish.yml, CITATION.bib, README.md, README_TEMPLATE.md, justfile
Main changes:
- Update to [voc4cat-template v0.8.7](https://github.com/nfdi4cat/voc4cat-template/releases/tag/v0.8.7) of which uses [voc4cat-tool v0.8.7](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.8.7) (from 0.8.5) in the actions. This fixes and improves adding mappings via the "Additional Concept Features" sheet.
- Related: #118.
- Improve the commands in the recently added `justfile` and add another command `xlsx` to re-build xlsx from turtle.
- Add the new template-related `README_TEMPLATE.md`.
=> Update underlying template & voc4cat-tool to v0.8.7

docs/conf.py, docs/docs_usage/guidelines.md, docs/index.md
This PR
* extends and heavily modifies the section "Singular vs. plural"
* weakens the recommendations for qualifiers in "Singular vs. plural" section from "should" to "may".
* re-formats section "Lower vs. capital letters"
* announces the new [kanban project board](https://github.com/orgs/nfdi4cat/projects/11) in the banner and adds a link to the sidebar
Closes #114
=> Revise "Singular vs. plural" section in guidelines & add link to kanban board

.github/workflows/ci-pr.yml, .github/workflows/merge.yml, .github/workflows/publish.yml, justfile
[Release v0.8.8](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.8.8) of voc4cat-tool fixes a bug that broke our workflow runs (affected only today).
This update also improves and extends the commands in the `justfile`.
=> Update underlying template & voc4cat-tool to v0.8.8

.github/CODEOWNERS
It does not make sense to request reviews of technical details from the voc4cat-curators team which should be responsible only for the vocabulary contents not the operation.
=> Split code ownership for gh-actions and vocabulary

.github/CODEOWNERS
Follow-up of #131:
Changing the xslx-template has to be done in careful coordination with voc4cat-tool and gh-action changes. This requires more expertise on how all tools in voc4cat play together than the members of the vocabulary-curator team should have. So this moves the ownership from the curator team to the tool developer.
=> Move code ownership for templates to dalito

.github/workflows/ci-pr.yml, .github/workflows/merge.yml, .github/workflows/publish.yml, justfile, templates/README.md
- Adds nicer and more consistent styling to the auto-created xlsx vocabulary file.
- Switches to CURIE-notation by default.
- For columns where the Id is not directly besides the preferred label column we add now the preferred label as a qualifier `voc4cat:0000141 (liquid chromatography)` also helps a lot with quickly seeing what an ID stands for.
- Note that the sheet "Prefixes" is now read-only. If you need certain prefixes we have to add them to ` idranges.toml`. This way they are shared among allo users of voc4cat. Please make a pull request if you need a prefix not yet present.
Closes #133
=> Update underlying template & voc4cat-tool to v0.9.0

.github/workflows/ci-pr.yml
This will be helpful in bigger PRs where the user (and reviewers) need access to an xlsx-file with all changes from the PR (for example in #151). The updated xlsx file is included in the job-artifact that can be downloaded on the job´s summary page.
=> Re-build updated xlsx in PRs

.github/workflows/publish.yml, docs/index.md, idranges.toml
Adds `--config idrange.toml` to the command for the conversion to xml. Without the config the prefix "voc4cat" is unknown. This  caused the failure of the publish job for Release v2025-05-21. Since we haven't created releases for quite some time this issue was not noticed before.
This PR fixes the underlying issue of #171.
=> Supply idranges.toml config for conversion to xml

docs/requirements.in, docs/requirements.txt
This PR addresses reported security vulnerabilities for requests<2.32.4 and urllib3<2.5.0 by updating them. 
It also updates Sphinx to the latest version 8.2.3 (from 8.1.3).
=> Update Sphinx and dependencies for docs

idranges.toml
Hi @b-elisa,
Thanks for your interest in contributing to voc4cat. 😸
This reserves the IDs from 8061 to 8080 for you.
While it should work to contribute without a real name or ORCID (no one tested before you), we cannot add you to the contributors of the Zenodo publication then. But you can later on submit your name or ORCID if you change your mind.
Closes #187
=> Add idrange for b-elisa
