nfdi4cat/voc4cat

- idranges.toml
First minimal version with @nmoust and myself as contributors.
Closes #7
> Add config file to reserve IDs for contributors

- vocabularies/voc4cat/concept_scheme.ttl
The fix is done directly in turtle.
Closes #13
> Fix url of publisher and creator.

- .zenodo.json
- README.md
- inbox-excel-vocabs/README.md
- Adapt zenodo metadata in `.zenodo.json` file to this repository.
- Update/improve READMEs
> Adapt zenodo metadata; improve and update READMEs

- README.md
> Fix link to iri-design

- .zenodo.json
- idranges.toml
@markdoerr - Your range of reserved IDs is [6001..7000]. Thanks for joining the team!
Closes #29
> ID request

- .github/workflows/merge.yml
- .github/workflows/publish.yml
Adresses #26. 
To fully support xml/rdf the w3id.org redirect config needs adjustment.
> Add xml/rdf ouput to merge & publish jobs

- idranges.toml
> Reserve 100 IDs for schumannj

- .zenodo.json
- CITATION.bib
@schumannj is the affiliation correct?
> Fix CITATION.bib & update contributors for Zenodo

- idranges.toml
IDs from 7201 to 7300 are reserved for you.
If you want to add an ORCID later just submit a PR,
Closes #51
> IDs for RoreKekse

- README.md
Follow-up of discussion in #67.
> Add note on small/big contributions.

- .zenodo.json
- README.md
- idranges.toml
The readme was not pointing to the DOI for all versions. This also adds Zenodo-metadata for M. Götte.
> Fix link to latest DOI, fix author metadata

- idranges.toml
This PR reserves IDs 7301 to 7320 for @khatamirad.
Closes #79
> Add irdrange for khatamirad

- idranges.toml
This PR reserves IDs 7321 to 7370 for @philippstangl. Thanks for reaching out and the interest in using voc4cat!
Closes #84
> Add idrange for philippstangl

- .github/workflows/merge.yml
> Fix action-trigger to also build on docs-changes

- docs/index.md
This was an oversight in #101. Caching was hiding the problem in my local tests.
> Fix ref to SKOS icon

- docs/conf.py
- docs/index.md
- Announcement changed to new release
- Font/text in bottom of cards adjusted to distract less from the cards header
> Homepage tweaks: Announcement, font in cards

- idranges.toml
This PR assigns 20 IDs to Sofia Angeli (IDs: 7371-7390) and 400 IDs to @HendrikBorgelt (IDs: 7391-7790).
Closes #135 
Closes #136
> ID assigned to Sofia Angeli and Hendrik Borgelt

- idranges.toml
Hi Franzi, nice to see you here!
This PR reserves the IDs from 7791 to 7850 for @FranziFlecken. If you need more IDs in the future just ask.
Closes #143
> Add idrange for Franzi

- docs/conf.py
- docs/index.md
Updates the documentation for the release.
> Prepare Release 2025-05-21

- docs/conf.py
- docs/docs_maintenance/handling-ID-requests.md
- docs/index.md
After fixing the publish pipeline in #172, we are ready to make a successful new release.
This PR also adds a note to the documentation that "Release 2025-05-21" was yanked.
Closes #171
> Prepare Release 2025-05-22

- idranges.toml
Hello Carla @carla-terboven,
Thanks for your interest in contributing to voc4cat. 😸
This reserves the IDs from 8081 to 8100 for you.
Closes #190
> IDs for carla-terboven

- CONTRIBUTING.md
Nikos, could you have a look at this one? I'll wait for your approval.
We could also make it even more minimal to avoid future alignment-issues with the docs. On the other hand it may be nice to have a concise summary with partial repetition like in this draft.
Closes #158
> Add CONTRIBUTING.md for GitHub compliance
